services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: docintel-postgres

    environment:
      POSTGRES_DB: docintel
      POSTGRES_USER: docintel
      POSTGRES_PASSWORD: docintel_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: